### ISSUE TITLE
objectGraph = ObjectGraph.create(new RootModule(this));

### ISSUE THREAD

**Issue by tamsir** [glomadrian/MvpCleanArchitecture#1]
Hello,
Very nice project
But when I try to execute I have a bug.
I do 1change : turning minSDKVersion from 21 to 14.
Caused by: java.lang.UnsupportedOperationException: No no-args constructor on com.github.glomadrian.mvpcleanarchitecture.app.dependencyinjection.ActivityModule$$ModuleAdapter
Any Ideas. Thank

**Comment by pratamawijaya** [comment]
I have too, got same bug, but still on miSDK 21 not 14

https://gist.github.com/pratamawijaya/f7ba4c669a49846b4f95

**Comment by glomadrian** [comment]
The bug was solved in the last comit, there was an error with the Activity module, thanks for the feedback

**Comment by tamsir** [comment]
Thanks glomadrian. useful project
